using Cognexa.Application;
using Cognexa.Infrastructure;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.DependencyInjection;
using Cognexa.Worker;
var builder = Host.CreateApplicationBuilder(args);
builder.Services.AddApplication().AddInfrastructure(builder.Configuration);
builder.Services.AddScoped<Cognexa.Application.Compartilhado.IUsuarioAtual, UsuarioDoWorker>();
builder.Services.AddScoped<Cognexa.Application.Usuarios.IIdentidadeAtual, UsuarioDoWorker>();
await builder.Build().RunAsync();
