using Cognexa.Application;
using Cognexa.Infrastructure;
using Cognexa.WebApi;
using Microsoft.AspNetCore.Diagnostics.HealthChecks;
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddApplication().AddInfrastructure(builder.Configuration);
builder.Services.AddProblemDetails(options => options.CustomizeProblemDetails = context => context.ProblemDetails.Extensions["traceId"] = context.HttpContext.TraceIdentifier);
builder.Services.AddExceptionHandler<TratamentoDeErros>();
builder.Services.Configure<Microsoft.AspNetCore.Routing.RouteHandlerOptions>(options => options.ThrowOnBadRequest = true);
builder.Services.AddHttpContextAccessor();
builder.Services.AddScoped<UsuarioAtual>();
builder.Services.AddScoped<Cognexa.Application.Compartilhado.IUsuarioAtual>(p => p.GetRequiredService<UsuarioAtual>());
builder.Services.AddScoped<Cognexa.Application.Usuarios.IIdentidadeAtual>(p => p.GetRequiredService<UsuarioAtual>());
builder.Services.AddAuthentication("Identidade").AddScheme<AutenticacaoOptions, AutenticacaoHandler>("Identidade", options => builder.Configuration.GetSection("Autenticacao").Bind(options));
builder.Services.AddAuthorization();
var app = builder.Build();
app.UseExceptionHandler();
app.UseStatusCodePages();
app.UseAuthentication();
app.UseAuthorization();
app.MapUsuarios();
app.MapBiblioteca();
app.MapAnotacoes();
app.MapConhecimento();
app.MapRevisoes();
app.MapInteligencia();
app.MapHealthChecks("/health/live", new HealthCheckOptions { Predicate = _ => false });
app.MapHealthChecks("/health/ready", new HealthCheckOptions { Predicate = check => check.Tags.Contains("ready") });
app.Run();
public partial class Program;
