// <auto-generated />
using System;
using Cognexa.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cognexa.Infrastructure.Persistencia.Migrations
{
    [DbContext(typeof(CognexaDbContext))]
    [Migration("20261007161928_Biblioteca")]
    partial class Biblioteca
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cognexa.Domain.Biblioteca.Autor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdLivro")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("IdLivro");

                    b.ToTable("Autor");
                });

            modelBuilder.Entity("Cognexa.Domain.Biblioteca.Capitulo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdLivro")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdLivro", "IdUsuario");

                    b.HasIndex("IdLivro", "Ordem")
                        .IsUnique();

                    b.ToTable("Capitulo");
                });

            modelBuilder.Entity("Cognexa.Domain.Biblioteca.Leitura", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DataDeConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DataDeInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdLivro")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<string>("Motivo")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("PaginaAtual")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdLivro", "IdUsuario")
                        .IsUnique();

                    b.HasIndex("IdUsuario", "Status");

                    b.ToTable("Leitura");
                });

            modelBuilder.Entity("Cognexa.Domain.Biblioteca.Livro", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Capa")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Edicao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<string>("Isbn")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("TotalDePaginas")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Livro");
                });

            modelBuilder.Entity("Cognexa.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Cognexa.Infrastructure.Identidade.VinculoDeIdentidade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdIdentidade")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdIdentidade")
                        .IsUnique();

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("VinculoDeIdentidade");
                });

            modelBuilder.Entity("Cognexa.Domain.Biblioteca.Autor", b =>
                {
                    b.HasOne("Cognexa.Domain.Biblioteca.Livro", null)
                        .WithMany("Autores")
                        .HasForeignKey("IdLivro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cognexa.Domain.Biblioteca.Capitulo", b =>
                {
                    b.HasOne("Cognexa.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cognexa.Domain.Biblioteca.Livro", null)
                        .WithMany()
                        .HasForeignKey("IdLivro", "IdUsuario")
                        .HasPrincipalKey("Id", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cognexa.Domain.Biblioteca.Leitura", b =>
                {
                    b.HasOne("Cognexa.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cognexa.Domain.Biblioteca.Livro", null)
                        .WithOne()
                        .HasForeignKey("Cognexa.Domain.Biblioteca.Leitura", "IdLivro", "IdUsuario")
                        .HasPrincipalKey("Cognexa.Domain.Biblioteca.Livro", "Id", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cognexa.Domain.Biblioteca.Livro", b =>
                {
                    b.HasOne("Cognexa.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Cognexa.Domain.Usuarios.Usuario", b =>
                {
                    b.OwnsOne("Cognexa.Domain.Usuarios.PreferenciasDoUsuario", "Preferencias", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Idioma")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<int>("MetaDiariaEmMinutos")
                                .HasColumnType("integer");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Preferencias")
                        .IsRequired();
                });

            modelBuilder.Entity("Cognexa.Infrastructure.Identidade.VinculoDeIdentidade", b =>
                {
                    b.HasOne("Cognexa.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Cognexa.Domain.Biblioteca.Livro", b =>
                {
                    b.Navigation("Autores");
                });
#pragma warning restore 612, 618
        }
    }
}
