// <auto-generated />
using System;
using Cognexa.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cognexa.Infrastructure.Persistencia.Migrations
{
    [DbContext(typeof(CognexaDbContext))]
    [Migration("20261007162027_Conhecimento")]
    partial class Conhecimento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cognexa.Domain.Anotacoes.Anotacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Comentario")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<DateTimeOffset>("DataDeCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("IdCapitulo")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdLivro")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("Pagina")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("TrechoOriginal")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.HasKey("Id");

                    b.HasIndex("IdLivro", "IdUsuario");

                    b.HasIndex("IdCapitulo", "IdLivro", "IdUsuario");

                    b.HasIndex("IdUsuario", "IdLivro", "Tipo", "Pagina");

                    b.ToTable("Anotacao");
                });

            modelBuilder.Entity("Cognexa.Domain.Biblioteca.Autor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdLivro")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("IdLivro");

                    b.ToTable("Autor");
                });

            modelBuilder.Entity("Cognexa.Domain.Biblioteca.Capitulo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdLivro")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdLivro", "IdUsuario");

                    b.HasIndex("IdLivro", "Ordem")
                        .IsUnique();

                    b.ToTable("Capitulo");
                });

            modelBuilder.Entity("Cognexa.Domain.Biblioteca.Leitura", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DataDeConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DataDeInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdLivro")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<string>("Motivo")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("PaginaAtual")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdLivro", "IdUsuario")
                        .IsUnique();

                    b.HasIndex("IdUsuario", "Status");

                    b.ToTable("Leitura");
                });

            modelBuilder.Entity("Cognexa.Domain.Biblioteca.Livro", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Capa")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Edicao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<string>("Isbn")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("TotalDePaginas")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Livro");
                });

            modelBuilder.Entity("Cognexa.Domain.Conhecimento.AplicacaoPratica", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<Guid>("IdAprendizado")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<int>("Origem")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdAprendizado", "IdUsuario");

                    b.HasIndex("IdUsuario", "IdAprendizado");

                    b.ToTable("AplicacaoPratica");
                });

            modelBuilder.Entity("Cognexa.Domain.Conhecimento.Aprendizado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<DateTimeOffset>("DataDeCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<int>("Origem")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Aprendizado");
                });

            modelBuilder.Entity("Cognexa.Domain.Conhecimento.Conceito", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario", "Nome")
                        .IsUnique();

                    b.ToTable("Conceito");
                });

            modelBuilder.Entity("Cognexa.Domain.Conhecimento.ConceitoDoAprendizado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdAprendizado")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdConceito")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdAprendizado", "IdConceito")
                        .IsUnique();

                    b.HasIndex("IdAprendizado", "IdUsuario");

                    b.HasIndex("IdConceito", "IdUsuario");

                    b.ToTable("ConceitoDoAprendizado");
                });

            modelBuilder.Entity("Cognexa.Domain.Conhecimento.FonteDoAprendizado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdAnotacao")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdAprendizado")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdLivro")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdAprendizado", "IdAnotacao")
                        .IsUnique();

                    b.HasIndex("IdAprendizado", "IdUsuario");

                    b.HasIndex("IdLivro", "IdUsuario");

                    b.HasIndex("IdAnotacao", "IdLivro", "IdUsuario");

                    b.ToTable("FonteDoAprendizado");
                });

            modelBuilder.Entity("Cognexa.Domain.Conhecimento.RelacaoEntreConceitos", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdConceitoDestino")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdConceitoOrigem")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdConceitoDestino", "IdUsuario");

                    b.HasIndex("IdConceitoOrigem", "IdUsuario");

                    b.HasIndex("IdUsuario", "IdConceitoOrigem", "IdConceitoDestino", "Tipo")
                        .IsUnique();

                    b.ToTable("RelacaoEntreConceitos");
                });

            modelBuilder.Entity("Cognexa.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Cognexa.Infrastructure.Identidade.VinculoDeIdentidade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdIdentidade")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdIdentidade")
                        .IsUnique();

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("VinculoDeIdentidade");
                });

            modelBuilder.Entity("Cognexa.Domain.Anotacoes.Anotacao", b =>
                {
                    b.HasOne("Cognexa.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cognexa.Domain.Biblioteca.Livro", null)
                        .WithMany()
                        .HasForeignKey("IdLivro", "IdUsuario")
                        .HasPrincipalKey("Id", "IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cognexa.Domain.Biblioteca.Capitulo", null)
                        .WithMany()
                        .HasForeignKey("IdCapitulo", "IdLivro", "IdUsuario")
                        .HasPrincipalKey("Id", "IdLivro", "IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Cognexa.Domain.Biblioteca.Autor", b =>
                {
                    b.HasOne("Cognexa.Domain.Biblioteca.Livro", null)
                        .WithMany("Autores")
                        .HasForeignKey("IdLivro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cognexa.Domain.Biblioteca.Capitulo", b =>
                {
                    b.HasOne("Cognexa.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cognexa.Domain.Biblioteca.Livro", null)
                        .WithMany()
                        .HasForeignKey("IdLivro", "IdUsuario")
                        .HasPrincipalKey("Id", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cognexa.Domain.Biblioteca.Leitura", b =>
                {
                    b.HasOne("Cognexa.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cognexa.Domain.Biblioteca.Livro", null)
                        .WithOne()
                        .HasForeignKey("Cognexa.Domain.Biblioteca.Leitura", "IdLivro", "IdUsuario")
                        .HasPrincipalKey("Cognexa.Domain.Biblioteca.Livro", "Id", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cognexa.Domain.Biblioteca.Livro", b =>
                {
                    b.HasOne("Cognexa.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Cognexa.Domain.Conhecimento.AplicacaoPratica", b =>
                {
                    b.HasOne("Cognexa.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cognexa.Domain.Conhecimento.Aprendizado", null)
                        .WithMany()
                        .HasForeignKey("IdAprendizado", "IdUsuario")
                        .HasPrincipalKey("Id", "IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Cognexa.Domain.Conhecimento.Aprendizado", b =>
                {
                    b.HasOne("Cognexa.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Cognexa.Domain.Conhecimento.Conceito", b =>
                {
                    b.HasOne("Cognexa.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Cognexa.Domain.Conhecimento.ConceitoDoAprendizado", b =>
                {
                    b.HasOne("Cognexa.Domain.Conhecimento.Aprendizado", null)
                        .WithMany("Conceitos")
                        .HasForeignKey("IdAprendizado", "IdUsuario")
                        .HasPrincipalKey("Id", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cognexa.Domain.Conhecimento.Conceito", null)
                        .WithMany()
                        .HasForeignKey("IdConceito", "IdUsuario")
                        .HasPrincipalKey("Id", "IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Cognexa.Domain.Conhecimento.FonteDoAprendizado", b =>
                {
                    b.HasOne("Cognexa.Domain.Conhecimento.Aprendizado", null)
                        .WithMany("Fontes")
                        .HasForeignKey("IdAprendizado", "IdUsuario")
                        .HasPrincipalKey("Id", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cognexa.Domain.Biblioteca.Livro", null)
                        .WithMany()
                        .HasForeignKey("IdLivro", "IdUsuario")
                        .HasPrincipalKey("Id", "IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cognexa.Domain.Anotacoes.Anotacao", null)
                        .WithMany()
                        .HasForeignKey("IdAnotacao", "IdLivro", "IdUsuario")
                        .HasPrincipalKey("Id", "IdLivro", "IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Cognexa.Domain.Conhecimento.RelacaoEntreConceitos", b =>
                {
                    b.HasOne("Cognexa.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cognexa.Domain.Conhecimento.Conceito", null)
                        .WithMany()
                        .HasForeignKey("IdConceitoDestino", "IdUsuario")
                        .HasPrincipalKey("Id", "IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cognexa.Domain.Conhecimento.Conceito", null)
                        .WithMany()
                        .HasForeignKey("IdConceitoOrigem", "IdUsuario")
                        .HasPrincipalKey("Id", "IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Cognexa.Domain.Usuarios.Usuario", b =>
                {
                    b.OwnsOne("Cognexa.Domain.Usuarios.PreferenciasDoUsuario", "Preferencias", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Idioma")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<int>("MetaDiariaEmMinutos")
                                .HasColumnType("integer");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Preferencias")
                        .IsRequired();
                });

            modelBuilder.Entity("Cognexa.Infrastructure.Identidade.VinculoDeIdentidade", b =>
                {
                    b.HasOne("Cognexa.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Cognexa.Domain.Biblioteca.Livro", b =>
                {
                    b.Navigation("Autores");
                });

            modelBuilder.Entity("Cognexa.Domain.Conhecimento.Aprendizado", b =>
                {
                    b.Navigation("Conceitos");

                    b.Navigation("Fontes");
                });
#pragma warning restore 612, 618
        }
    }
}
